// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjLXHA4ti3mKNbgC11e0hEtd5NLw8jTu4',
    appId: '1:359590499162:web:d2040c8215d92d963b9963',
    messagingSenderId: '359590499162',
    projectId: 'reflectiverespite',
    authDomain: 'reflectiverespite.firebaseapp.com',
    storageBucket: 'reflectiverespite.appspot.com',
    measurementId: 'G-WSHFLPGH04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNI7LShL_-A6u-hiYT-YxihNSTqnEgmVA',
    appId: '1:359590499162:android:b18a735c95d604e83b9963',
    messagingSenderId: '359590499162',
    projectId: 'reflectiverespite',
    storageBucket: 'reflectiverespite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN09rh-fSxAxFp5GuoKjB3Yb0Y_VAky80',
    appId: '1:359590499162:ios:1830a6f69e23b4383b9963',
    messagingSenderId: '359590499162',
    projectId: 'reflectiverespite',
    storageBucket: 'reflectiverespite.appspot.com',
    iosBundleId: 'com.example.startPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN09rh-fSxAxFp5GuoKjB3Yb0Y_VAky80',
    appId: '1:359590499162:ios:d74602e853be1f2f3b9963',
    messagingSenderId: '359590499162',
    projectId: 'reflectiverespite',
    storageBucket: 'reflectiverespite.appspot.com',
    iosBundleId: 'com.example.startPage.RunnerTests',
  );
}
